# Generated by Django 5.1.15 on 2026-07-26 02:48

import checks.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "audit_id",
                    models.CharField(
                        default=checks.models.generate_audit_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "raw_url",
                    models.TextField(help_text="URL exactly as submitted, pre-normalization"),
                ),
                (
                    "normalized_url",
                    models.CharField(
                        db_index=True,
                        help_text="Lowercased host, stripped default port, sorted query params",
                        max_length=2048,
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        help_text="Correlates to structured log lines (TRD §9)",
                        max_length=64,
                    ),
                ),
                (
                    "result",
                    models.JSONField(help_text="Full result: availability/performance/seo_signals/security_headers"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "Completed"), ("failed", "Failed")],
                        help_text="completed | failed — failed audits still get a row",
                        max_length=16,
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(help_text="When the check actually ran"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audits",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["-created_at"], name="idx_audits_created_at")],
            },
        ),
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "monitor_id",
                    models.CharField(
                        default=checks.models.generate_monitor_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "owner_key",
                    models.CharField(
                        db_index=True,
                        help_text="X-Client-Key header value (App Flow §0.1)",
                        max_length=64,
                    ),
                ),
                ("raw_url", models.TextField(help_text="URL as submitted")),
                ("normalized_url", models.CharField(max_length=2048)),
                (
                    "interval_seconds",
                    models.IntegerField(help_text="Check interval (min: MONITOR_MIN_INTERVAL_SECONDS)"),
                ),
                ("webhook_url", models.TextField(help_text="Alert destination URL")),
                (
                    "latency_threshold_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="NULL = no latency-based DEGRADED check, only up/down",
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING_FIRST_CHECK", "Pending First Check"),
                            ("UP", "Up"),
                            ("DOWN", "Down"),
                            ("DEGRADED", "Degraded"),
                        ],
                        default="PENDING_FIRST_CHECK",
                        max_length=24,
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="NULL until first scheduled check",
                        null=True,
                    ),
                ),
                (
                    "next_check_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Display-only estimate, real schedule in django-celery-beat",
                        null=True,
                    ),
                ),
                (
                    "periodic_task_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Points to django_celery_beat_periodictask.id (no DB FK — §1 note)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "monitors",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["normalized_url"], name="idx_monitors_normalized_url")],
                "constraints": [
                    models.UniqueConstraint(fields=("owner_key", "normalized_url"), name="unique_owner_url")
                ],
            },
        ),
        migrations.CreateModel(
            name="MonitorCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(help_text="State snapshot as of this check", max_length=24),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(blank=True, help_text="NULL on outright failure", null=True),
                ),
                (
                    "status_code",
                    models.IntegerField(blank=True, help_text="NULL on total unreachability", null=True),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        help_text="TRD §5 error code, populated only on failure",
                        max_length=32,
                        null=True,
                    ),
                ),
                ("checked_at", models.DateTimeField()),
                (
                    "monitor",
                    models.ForeignKey(
                        db_column="monitor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="checks.monitor",
                    ),
                ),
            ],
            options={
                "db_table": "monitor_checks",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["monitor", "-checked_at"],
                        name="idx_monitor_checks_mid_cat",
                    )
                ],
            },
        ),
    ]
